---
cert: "/Users/yuantong/Documents/定制项目/中央民族大学/shanglian_front.pem"
pfx: "/Users/yuantong/Documents/定制项目/中央民族大学/shanglian_front.pfx"
private_key: "12345678"
product_id: 3
scheme: "https"
interface_ip: "192.168.0.191"
app_id: "srunsoft"
app_secret: "ba62f23e6212790052f387ee7af2943e4cfcece0"
log_path: "runtime"
port: "8890"
pay_type: 9
pay_type_id: 103
tls_pem: "/Users/yuantong/Documents/证书/12574526_yuantong.pro_nginx/yuantong.pro.pem"
tls_key: "/Users/yuantong/Documents/证书/12574526_yuantong.pro_nginx/yuantong.pro.key"
is_https: false
